   138.4ms (setup:799): 2023-08-05 14:23:43
   138.5ms (setup:800): /usr/bin/pipx install python-dateutil
   138.6ms (setup:801): pipx version is 1.2.0
   138.6ms (setup:802): Default python interpreter is '/usr/bin/python'
   138.6ms (mkdir:81): creating directory /home/nai/.local/pipx/venvs
   138.7ms (mkdir:81): creating directory /home/nai/.local/bin
   138.8ms (mkdir:81): creating directory /home/nai/.local/pipx/.cache
   138.9ms (setup:810): Adding CACHEDIR.TAG to cache directory
   139.7ms (package_name_from_spec:322): Determined package name: python-dateutil
   139.7ms (package_name_from_spec:323): Package name determined in 0.0s
   140.1ms (run_subprocess:173): running /usr/bin/python -m venv --without-pip /home/nai/.local/pipx/venvs/python-dateutil
   189.5ms (run_subprocess:186): stdout:
   189.6ms (run_subprocess:188): stderr:
   189.6ms (run_subprocess:189): returncode: 0
   190.1ms (run_subprocess:173): running /usr/bin/python -m venv --clear /home/nai/.local/pipx/shared
  3704.1ms (run_subprocess:186): stdout:
  3704.2ms (run_subprocess:188): stderr:
  3704.2ms (run_subprocess:189): returncode: 0
  3704.5ms (upgrade:91): Upgrading shared libraries in /home/nai/.local/pipx/shared
  3704.9ms (run_subprocess:173): running /home/nai/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install --force-reinstall -q --upgrade pip setuptools wheel
  8906.1ms (run_subprocess:186): stdout:
  8906.2ms (run_subprocess:188): stderr:
  8906.2ms (run_subprocess:189): returncode: 0
  8906.6ms (run_subprocess:173): running /home/nai/.local/pipx/venvs/python-dateutil/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  8919.9ms (run_subprocess:186): stdout: /home/nai/.local/pipx/venvs/python-dateutil/lib/python3.11/site-packages
  8920.0ms (run_subprocess:189): returncode: 0
  8920.3ms (run_subprocess:173): running /home/nai/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
  8934.0ms (run_subprocess:186): stdout: /home/nai/.local/pipx/shared/lib/python3.11/site-packages
  8934.1ms (run_subprocess:189): returncode: 0
  8934.4ms (run_subprocess:173): running /home/nai/.local/pipx/venvs/python-dateutil/bin/python --version
  8941.1ms (run_subprocess:186): stdout: Python 3.11.3
  8941.1ms (run_subprocess:188): stderr:
  8941.2ms (run_subprocess:189): returncode: 0
  8941.3ms (_parsed_package_to_package_or_url:147): cleaned package spec: python-dateutil
  8941.7ms (run_subprocess:173): running /home/nai/.local/pipx/venvs/python-dateutil/bin/python -m pip install python-dateutil
 10516.8ms (run_subprocess:189): returncode: 0
 10517.9ms (run_subprocess:173): running <fetch_info_in_venv commands>
 10543.5ms (run_subprocess:186): stdout: {"sys_path": ["/usr/lib/python311.zip", "/usr/lib/python3.11", "/usr/lib/python3.11/lib-dynload", "/home/nai/.local/pipx/venvs/python-dateutil/lib/python3.11/site-packages", "/home/nai/.local/pipx/shared/lib/python3.11/site-packages"], "python_version": "3.11.3", "environment": {"implementation_name": "cpython", "implementation_version": "3.11.3", "os_name": "posix", "platform_machine": "x86_64", "platform_release": "6.1.39-3-lts", "platform_system": "Linux", "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 10:12:55 +0000", "python_full_version": "3.11.3", "platform_python_implementation": "CPython", "python_version": "3.11", "sys_platform": "linux"}}
 10543.6ms (run_subprocess:189): returncode: 0
 10547.9ms (get_venv_metadata_for_package:316): get_venv_metadata_for_package: 31ms
 10548.0ms (_parsed_package_to_package_or_url:147): cleaned package spec: python-dateutil
 10548.3ms (rmdir:55): removing directory /home/nai/.local/pipx/venvs/python-dateutil
 10550.5ms (cli:866): PipxError: No apps associated with package python-dateutil or its dependencies. If you are attempting
to install a library, pipx should not be used. Consider using pip or a similar tool
instead.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipx/main.py", line 214, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pipx/commands/install.py", line 69, in install
    run_post_install_actions(
  File "/usr/lib/python3.11/site-packages/pipx/commands/common.py", line 357, in run_post_install_actions
    raise PipxError(
pipx.util.PipxError: No apps associated with package python-dateutil or its dependencies. If you are attempting
to install a library, pipx should not be used. Consider using pip or a similar tool
instead.
 10551.3ms (cli:874): pipx finished.
